id: "cb74ad52-7ba6-4495-b92d-c5a0b289ed52"
slug: "you-can-edit-this-draft-when-ready-submit-it-to-the-editorial-team"
title: "You can edit this draft. When ready, submit it to the editorial team"
category: "Draft"
status: "published"
primary_author: "devyendarm"
