id: "da302c33-a94e-4639-8a6b-53c7148c2f15"
slug: "from-touchpoints-to-transitions-a-journey-centric-approach-to-customer-analytics"
title: "From Touchpoints to Transitions: A Journey-Centric Approach to Customer Analytics"
status: "idea"
primary_author: "devyendarm"
